#!/usr/bin/env bash
# build_paper.sh — convert Markdown/DOCX -> IEEEtran two-column LaTeX -> PDF.
#
# Mechanical pipeline only (the reliable ~80%): pandoc converts the BODY, this
# script wraps it in an IEEEtran skeleton (title/author/abstract/keywords/bib)
# and compiles with latexmk. Author block / floated figures / table-in-twocolumn
# / citation-key mapping are the manual ~20% — hand-touch per paper.
#
# Tools (global, ~/.local/bin): pandoc, latexmk, IEEEtran.cls/.bst (TinyTeX).
#
# Usage:
#   ./build_paper.sh [opts] <input.md|input.docx> [more inputs...]
# Options:
#   --class conference|journal   IEEEtran mode (default: conference)
#   --title  "..."               paper title
#   --author "A and B"           author names (IEEEtran \and-separated)
#   --affil  "Dept.\\ Univ."     affiliation block (LaTeX, use \\ for newline)
#   --abstract "..."             abstract text
#   --abstract-file FILE.tex     abstract from a file (LaTeX fragment)
#   --keywords "a, b, c"         IEEEkeywords line
#   --bib    refs.bib            BibTeX database (enables \cite + IEEEtran.bst)
#   --outdir DIR                 build dir (default: ./ieee-build)
#   -o NAME                      output stem (default: paper)
# Multiple inputs are concatenated in order (e.g. ch1.md ch2.md ...).

set -euo pipefail

CLASS=conference
TITLE="Title Placeholder"
AUTHOR="Anonymous"
AFFIL=""
ABSTRACT=""
ABSTRACT_FILE=""
KEYWORDS=""
BIB=""
OUTDIR="ieee-build"
OUT="paper"
INPUTS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --class) CLASS="$2"; shift 2;;
    --title) TITLE="$2"; shift 2;;
    --author) AUTHOR="$2"; shift 2;;
    --affil) AFFIL="$2"; shift 2;;
    --abstract) ABSTRACT="$2"; shift 2;;
    --abstract-file) ABSTRACT_FILE="$2"; shift 2;;
    --keywords) KEYWORDS="$2"; shift 2;;
    --bib) BIB="$2"; shift 2;;
    --outdir) OUTDIR="$2"; shift 2;;
    -o) OUT="$2"; shift 2;;
    -h|--help) sed -n '2,30p' "$0"; exit 0;;
    -*) echo "unknown option: $1" >&2; exit 2;;
    *) INPUTS+=("$1"); shift;;
  esac
done

[[ ${#INPUTS[@]} -ge 1 ]] || { echo "error: need >=1 input file" >&2; exit 2; }
command -v pandoc  >/dev/null || { echo "error: pandoc not found" >&2; exit 1; }
command -v latexmk >/dev/null || { echo "error: latexmk not found" >&2; exit 1; }

case "$CLASS" in
  conference) CLASSOPT="[conference]";;
  journal)    CLASSOPT="";;            # IEEEtran default = two-column journal
  *) echo "error: --class must be conference|journal" >&2; exit 2;;
esac

mkdir -p "$OUTDIR"
BODY="$OUTDIR/.body.tex"
: > "$BODY"

# --- pandoc: convert each input to a LaTeX body fragment ---
for f in "${INPUTS[@]}"; do
  [[ -f "$f" ]] || { echo "error: no such file: $f" >&2; exit 1; }
  EXTRA=()
  [[ "$f" == *.docx ]] && EXTRA+=(--extract-media="$OUTDIR/media")
  [[ -n "$BIB" ]] && EXTRA+=(--natbib)
  pandoc "$f" -t latex --wrap=preserve "${EXTRA[@]}" >> "$BODY"
  printf '\n\n' >> "$BODY"
done

# --- abstract source ---
ABS_TEX=""
if [[ -n "$ABSTRACT_FILE" ]]; then
  ABS_TEX="$(cat "$ABSTRACT_FILE")"
elif [[ -n "$ABSTRACT" ]]; then
  ABS_TEX="$ABSTRACT"
fi

# --- bib: stage into outdir so bibtex finds it ---
BIBSTEM=""
if [[ -n "$BIB" ]]; then
  [[ -f "$BIB" ]] || { echo "error: no such bib: $BIB" >&2; exit 1; }
  cp -f "$BIB" "$OUTDIR/"
  BIBSTEM="$(basename "$BIB" .bib)"
fi

# --- assemble IEEEtran skeleton ---
TEX="$OUTDIR/$OUT.tex"
{
  printf '%% Generated by build_paper.sh — IEEEtran %s.\n' "$CLASS"
  printf '\\documentclass%s{IEEEtran}\n' "$CLASSOPT"
  cat <<'PREAMBLE'
\usepackage[numbers,sort&compress]{natbib}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\usepackage{textcomp}
\usepackage{booktabs}
\usepackage{array}
\usepackage{xurl}
\usepackage{balance}
\usepackage[T1]{fontenc}
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage[hidelinks]{hyperref}
\usepackage{etoolbox}
% Upright run-in \paragraph headings (keep a) label + colon); variables stay italic in math mode
\patchcmd{\paragraph}{\itshape}{\upshape}{}{}

\begin{document}

PREAMBLE
  printf '\\title{%s}\n\n' "$TITLE"
  printf '\\author{\\IEEEauthorblockN{%s}' "$AUTHOR"
  [[ -n "$AFFIL" ]] && printf '\n\\IEEEauthorblockA{%s}' "$AFFIL"
  printf '}\n\n\\maketitle\n\n'
  if [[ -n "$ABS_TEX" ]]; then
    printf '\\begin{abstract}\n%s\n\\end{abstract}\n\n' "$ABS_TEX"
  fi
  if [[ -n "$KEYWORDS" ]]; then
    printf '\\begin{IEEEkeywords}\n%s\n\\end{IEEEkeywords}\n\n' "$KEYWORDS"
  fi
  cat "$BODY"
  if [[ -n "$BIBSTEM" ]]; then
    printf '\n\\bibliographystyle{IEEEtranN}\n\\bibliography{%s}\n' "$BIBSTEM"
  fi
  printf '\n\\end{document}\n'
} > "$TEX"
rm -f "$BODY"

# --- compile ---
echo "==> compiling $TEX"
( cd "$OUTDIR" && env MPLCONFIGDIR=/tmp/mpl latexmk -pdf -interaction=nonstopmode -halt-on-error "$OUT.tex" >build.log 2>&1 ) || {
  echo "BUILD FAILED — last errors:" >&2
  grep -nE "File .* not found|^! |Emergency|Fatal" "$OUTDIR/build.log" | head -15 >&2
  exit 1
}
PAGES="$(command -v pdfinfo >/dev/null && pdfinfo "$OUTDIR/$OUT.pdf" | awk '/Pages/{print $2}')"
echo "BUILD OK -> $OUTDIR/$OUT.pdf (${PAGES:-?} pages)"
