declare -a PAIRS=(
 "d3null_target_is_t0_action|test_d3_null_target_is_legal_independent_of_t0_and_seeded"
 "d3null_target_may_be_illegal|test_d3_null_target_is_legal_independent_of_t0_and_seeded"
 "d3null_uses_train_rng|test_d3_null_target_is_legal_independent_of_t0_and_seeded"
 "d3null_scores_carry_t0|test_d3_null_target_is_legal_independent_of_t0_and_seeded"
 "d3null_key_dropped_from_hash|test_d3_null_version_hash_covers_the_null_identity"
 "manifest_ignores_dev_settings|test_d3_null_version_hash_covers_the_null_identity"
 "teacher_applied_at_zero_weight|test_teacher_weight_zero_reproduces_d0_bit_identically"
)
